### ISSUE TITLE
Deploy app to GKE

### ISSUE THREAD

**Issue by boiyaa** [mqtsuo02/react-native-graphql#18]
bur8787 supports you about deployment

**Comment by mqtsuo02** [comment]
## 作業履歴

- google-croud-sdkのインストール
- GCPアカウントの連携
- dockerの設定画面がらKubernetesツールのインストール

## GCP手順

プロジェクトディレクトリ直下で以下を実行

### Build the production image

```
gcloud container builds submit --tag=gcr.io/${PROJECT_ID}/graphql-demo:v1 .
```

listをチェック

```
gcloud container images list
```

### Create a Kubernetes cluster

```
gcloud container clusters create graphql-demo-cluster --num-nodes=2
```

デフォルトクラスタの設定

```
gcloud config set container/cluster graphql-demo-cluster
```

参考元 => https://cloud.google.com/community/tutorials/kotlin-springboot-container-engine
